yaml
version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
    commands:
      - echo Installing dependencies...
      - sudo apt-get update -y
  pre_build:
    commands:
      - echo Starting Docker services...
      - sudo service docker start
  build:
    commands:
      - echo Building and pushing Docker image...
      - sudo docker build -t my-kong .
      - sudo docker tag my-kong:latest <your-dockerhub-username>/my-kong:latest
      - sudo docker push <your-dockerhub-username>/my-kong:latest
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - appspec.yml
    - scripts/*
  discard-paths: yes
